


import 'package:igli_financial/view/more/My_Services/All_Services/Model/All_Services_model.dart';

List<BusinessSetupModel> businessSetupModel = [
  BusinessSetupModel(listTitle: "Private Limited Company Registration",subListTitlePay: "6193",pay: "Pay ₹499/-to get started",
    description: "Private limited company is the best option for entrepreneurs who have big dreams for their business. We can help you register your Pvt ltd company without hassle! With us, the entire process is online and you get guidance throughout the process. All you need to do is provide a few details and upload some documents, we will take care of the rest. We even get you PAN and TAN. Make sure you have a minimum of 2 directors to get started.",
    duration: "The process usually takes about 7-10 business days.",
    deliverables: "1. Directors Identification Number (Max 3)\n2. Digital Signature Certificate for directors and shareholders\n3. Memorandum of Association and Articles of Association\n4. PAN Number\n5. TAN Number\n6. Certificate of Incorporation.\n7. Name approval certificate\n8. Provident Fund Registration for Employer\n9. Employee State Insurance Registration for Employer\n10. Professional Tax Registration (Applicable only for Karnataka & Maharashtra}",
    penalty: "Yes",
    benefits: "1. There is a Limited risk to personal assets in Private Limited Company.\n2. Trading as a limited company helps to portray a professional image and enhance your reputation.",
    documents: "Scanned copies of:\n\n1. PAN\n\n2. ID Proof -Any One are accepted: Aadhaar card, Voters ID, passport (front & back), driving license (front & back) - Must not be Expired proof 3. Address Proof-Any one of this are accepted (Self-attested): Bank statement / Mobile bill / Telephone bill / Electricity bill - It must be the Current month (Not more than 30 days old) 4.Registered Office Address Proof- Electricity Bill / Gas Bill / Postpaid Mobile//Jio Prepaid Bill - Must be current month / period (Not more than 30 days old) 5. Passport size photograph 6. Specimen signature\n\nNote: Any one of the directors should self-attest the first three documents.",
    deliverablesTab: "1. Directors Identification Number (Max 3)\n2. Digital Signature Certificate for directors and shareholders\n3. Memorandum of Association and Articles of Association\n4. PAN Number\n5. TAN Number\n6. Certificate of Incorporation.\n7. Name approval certificate\n8. Provident Fund Registration for Employer\n9. Employee State Insurance Registration for Employer\n10. Professional Tax Registration (Applicable only for Karnataka & Maharashtra}",
  ),
  BusinessSetupModel(listTitle: "Start Limited Liability Partnership(LLP)",subListTitlePay: "7691",pay: "Pay ₹499/-to get started",
      description: "Enjoy the twin benefits of partnership structure and limited liability through a Limited Liability Partnership. We can help you register your LLP without hassle! With us, the entire process is online and you get guidance throughout the process. All you need to do is provide a few details and upload some documents, we will take care of the rest. We even get you PAN, TAN and help set up a current account. Make sure you have a minimum of 2 partners to get started.",
      duration: "The process usually takes about 35-40 business days.",
      deliverables: "1. Directors Identification Number (Max for 2 Partners)\n2. One Digital Signature Certificate for 1 applicant\n3. Company's Name Approval Certificate\n4. PAN Number\n5. TAN Number\n6. LLP Deed\n7. Certificate of Incorporation (CIN)",
      penalty:"Yes",
      benefits: "1. Low cost of registration\n2. Group resourcing and pooling of efforts increases productivity\n3. Capacity to Sue\n4. Flexibility Of Management\n5. No Limit On The Number Of Business Owners\n6. Convenient Formation With Minimum Contribution",
      documents: "Scanned copies required for Designated partners andPartners\n\n1. PAN\n2. ID Proof -Any One are accepted: Aadhaar card, Voters ID, passport (front & back), driving license (front & back) - Must not be Expired proof\n3. Address Proof-Any one of this are accepted (Self-attested): Bank statement / Mobile bill/ Telephone bill / Electricity bill - It must be the Current month (Not more than 30 days old)\n4. Registered Office Address Proof- Electricity Bill / Gas Bill / Postpaid Mobile//Jio Prepaid Bill - Must be current month / period (Not more than 30 days old)\n 5. Passport size photograph\n 6. Specimen signature\n\nNote: Any one of the directors should self-attest the first three documents.",
      deliverablesTab: "1. Directors Identification Number (Max for 2 Partners)\n2. One Digital Signature Certificate for 1 applicant\n3. Company's Name Approval Certificate\n4. PAN Number\n5. TAN Number\n6. LLP Deed\n7. Certificate of Incorporation (CIN)"
  ),
  BusinessSetupModel(listTitle: "Register a One Person Company",subListTitlePay: "4718",pay: "Pay ₹499/-to get started",
      description: "One person company is the best option for the entrepreneur who wants to take charge of their business. We can help you register your OPC without hassle! With us, the entire process is online and you get guidance throughout the process. All you need to do is provide a few details and upload some documents, we will take care of the rest. We even get you PAN, TAN and help set up a current account.",
      duration: "The process usually takes about 7-10 business days.",
      deliverables: "1. Directors Identification Number for 1 Directors\n2. Digital Signature Certificate for 1Directors\n3. Memorandum of Association and Articles of Association\n4. PAN Number\n5. TAN Number\n6. Certificate of Incorporation.\n7. Name approval certificate\n8. Provident Fund Registration for Employer\n9. Employee State Insurance Registration for Employer\n10. Professional Tax Registration (Applicable only for Karnataka & Maharashtra}",
      penalty: "Yes",
      benefits: "1. In the event of the death of the Managing member, all the shares and investments of the OPC are handed down to the nominee. \n2. A One Person Company has more relaxed and lessbinding compliance regulations. \n3. Helps in organising the unorganised proprietorship by giving it the same legal status of a private limited company.",
      documents: "Scanned copies of Director and Nominee:\n\n1. PAN\n2. ID Proof -Any One are accepted: Aadhaar card, Voters ID, passport (front & back), driving license (front & back) - Must not be Expired proof \n3. Address Proof-Any one of this are accepted (Self-attested): Bank statement / Mobile bill / Telephone bill / Electricity bill - It must be the Current month (Not more than 30 days old) \n4. Registered Office Address Proof- Electricity Bill / Gas Bill / Postpaid Mobile//Jio Prepaid Bill - Must be current month / period (Not more than 30 days old) \n5. Passport size photograph \n6. Specimen signature\n\nNote: Any one of the directors should self-attest the first three documents. Please note for OPC registration a Nominee is mandatory",
      deliverablesTab: "\n1. Directors Identification Number for 1 Directors \n2. Digital Signature Certificate for 1 Directors \n3. Memorandum of Association and Articles of Association\n4. PAN Number \n5. TAN Number\n6. Certificate of Incorporation.\n7. Name approval certificate\n8. Provident Fund Registration for Employer\n9. Employee State Insurance Registration for Employer \n10. Professional Tax Registration (Applicable only for Karnataka & Maharashtra}"

  ),
  BusinessSetupModel(listTitle: "NIDHI Company Registration",subListTitlePay: "52858",pay: "",
      description: "Start a nidhi company and provide financial assistance to your members hassle-free by using Vaskilsearch's expert service. Encourage your members/shareholders to save more money and invest them within the company. You can use this deposits to provide loans or advances, and to acquire government-issued stocks/bonds/debentures/ securities",
      duration: "",
      deliverables: "1. Directors Identification Number (Max 3) \n2. Digital Signature Certificate for directors and shareholders \n3. Memorandum of Association and Articles of Association\n4. PAN Number\n5. TAN Number\n6. Certificate of Incorporation.\n7. Name approval certificate \n8. Provident Fund Registration for Employer\n9. Employee State Insurance Registration for Employer \n10. Professional Tax Registration (Applicable only for Karnataka & Maharashtra}",
      penalty: "",
      benefits: "1. Members can borrow money at a cheaper rate \n2. Encourages savings among members \n3. Lesser formalities and risk \n4. Nidhi companies are easier to set up and need lesser capital",
      documents: "We need min 7 members in that 3 should be directors\n\n1. PAN\n2. ID Proof -Any One are accepted: Aadhaar card, Voters ID, passport (front & back), driving license (front & back) - Must not be Expired proof \n3. Address Proof-Any one of this are accepted (Self-attested): Bank statement / Mobile bill / Telephone bill / Electricity bill - It must be the Current month (Not more than 30 days old) \n4.Registered Office Address Proof- Electricity Bill / Gas Bill / Postpaid Mobile//Jio Prepaid Bill - Must be current month / period (Not more than 30 days old) \n5. Passport size photograph \n6. Specimen signature\n\nNote: Minimum Authorised capital required is 5 lakhs to incorporate a Nidhi company",
      deliverablesTab: "1. Directors Identification Number (Max 3) \n2. Digital Signature Certificate for directors and shareholders\n3. Memorandum of Association and Articles of Association\n4. PAN Number\n5. TAN Number\n6. Certificate of Incorporation.\n7. Name approval certificate \n8. Provident Fund Registration for Employer\n9. Employee State Insurance Registration for Employer \n10. Professional Tax Registration (Applicable only for Karnataka & Maharashtra}"
  ),
  BusinessSetupModel(listTitle: "Producer company Registration",subListTitlePay: "34798",pay: "",
      description: "A Company that is registered with the Ministry of Corporate Affairs (MCA), for the purpose of agricultural production and processing activities, is called a Producer Company. It comprises a committee of a minimum of 10 people and 2 institutions. Start a producer company without hassle using Vakilsearch service and enjoy the benefits of the company to lower the risks involved and reduce the liabilities of the members.",
      duration: "",
      deliverables: "\1. Directors Identification Number (Max 5)\n2. Digital Signature Certificate for directors and shareholders\n3. Memorandum of Association and Articles of Association\n4. PAN Number\n5. TAN Number\n6. Certificate of Incorporation.\n7. Name approval certificate\n8. Provident Fund Registration for Employer \n9. Employee State Insurance Registration for Employer\n10. Professional Tax Registration (Applicable only for Karnataka & Maharashtra}",
      penalty: "No",
      benefits: "1. Provides limited liability to members \n2. Members can enjoy lower costs, reduced risk and get access to better credit facilities \n3. It is a better way to manage the business",
      documents: "There should be minimum 10 members in that 5 should be directors and the required authorised capital is 5 lakhs\n\n1. PAN\n2. ID Proof -Any One are accepted: Aadhaar card, Voters ID, passport (front & back), driving license (front & back) - Must not be Expired proof \n3. Address Proof-Any one of this are accepted (Self-attested): Bank statement / Mobile bill/ Telephone bill / Electricity bill - It must be the Current month (Not more than 30 days old) \n4.Registered Office Address Proof- Electricity Bill / Gas Bill / Postpaid Mobile//Jio Prepaid Bill - Must be current month / period (Not more than 30 days old) \n5. Passport size photograph \n6. Specimen signature\n7. Producer certificate is mandatory",
      deliverablesTab:"1. Directors Identification Number (Max 5) 2. Digital Signature Certificate for directors and shareholders\n3. Memorandum of Association and Articles of Association\n4. PAN Number\n5. TAN Number\n6. Certificate of Incorporation.\n7. Name approval certificate \n8. Provident Fund Registration for Employer\n9. Employee State Insurance Registration for Employer \n10. Professional Tax Registration (Applicable only for Karnataka & Maharashtra}"

  ),
  BusinessSetupModel(listTitle: "Start a Partnership Firm",subListTitlePay: "7606",pay: "Pay ₹499/-to get started",
      description: "Partnership firm is one of the easiest type of business to set up and maintain. Our experts will draft your partnership deed with utmost care and help in registering your firm to ensure a strong base for your business. With us, the process is both online and offline. All you need to do is provide a few details and upload some documents, And the physical representation of the Partners at the time of registration is required at the local registrar office. We also help you register/ notarize the firm and guide you with post-registration compliances. Make sure you have a minimum of 2 partners to get started.",
      duration: "The process usually takes about 15-25 business days.",
      deliverables: "1. Partnership deed drafted by experts \n2. Certificate of Registration (Varies from state to state) 3. Acknowledgments for PAN and TAN application",
      penalty: "No",
      benefits: "1. It is very easy to start with simple procedures. \n2. With multiple perspectives and excessive knowledge, making decisions in a partnership firm can be very effective. \n3. It's easier and faster to convert into any other business structure if the partnership is registered.",
      documents: "Scanned copy of\n\n- PAN and Aadhaar card of all the partners (self-attested)\n- Recent electricity bill of the premises (Last month) \n- Rental agreement of the premises",
      deliverablesTab: "1. Partnership deed drafted by experts \n2. Certificate of Registration (Varies from state to state) \n3. Acknowledgments for PAN and TAN application"
  ),
];

List<BusinessSetupModel> licensesModel = [
  BusinessSetupModel(listTitle: "Get a Digital Signature Certificate",subListTitlePay: "1499",pay: "Pay ₹499/-to get started",
      description: "A digital signature certificate (DSC) is a digital key issued to confirm the identity of a person in online transactions. It helps prevent unauthorised use of your document and data. With DSC you can sign documents in a click of a button. No one can fake your DSC like they can fake your signature. It is mandatory to have a DSC for tasks like registering a company, e-Tendering, e-Procurement, and in other important government-related forms. With us, you can get your DSC easily in a few steps.",
      duration: "1. Dedicated RM for Guidance on the DSC procedure \n2. Digital Signature Certificate downloaded in USB Token",
      deliverables: "",
      penalty: "Yes",
      benefits: "1. It reduces cost and time \n2. The documents that are signed digitally cannot be edited or altered once it is signed. It makes the data secure and safe.\n3. It ensures better efficiency in a workflow. You can manage and track documents easily with less effort and time involved. \n4. Digital signatures provide the convenience of signing important documents wherever the customers are located.",
      documents: "Scanned copy of\n\n1. PAN CARD\n2. Aadhar Card (or) Driving License (Or) Voter Id \n3. Passport Size Photo",
      deliverablesTab: "1. Dedicated RM for Guidance on the DSC procedure \n2. Digital Signature Certificate downloaded in USB Token"),

  BusinessSetupModel(listTitle: "Apply for SSI/MSME Registration",subListTitlePay: "999",pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "ISO Cerification",subListTitlePay: "1999",pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Apply for Importer Exporter Code",subListTitlePay: "2010",pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
];
