



import 'package:igli_financial/view/more/My_Services/All_Services/Model/All_Services_model.dart';

List<BusinessSetupModel> corporateModel = [
  BusinessSetupModel(listTitle: "Get help from a Company Secretary for your Private Limited Company",subListTitlePay: "26458",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Get help from a Company Secretary for your Limited Liability Partnership",subListTitlePay: "5150",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
];

List<BusinessSetupModel> changesPvtModel = [
  BusinessSetupModel(listTitle: "Appointment of a Director",subListTitlePay: "4815",pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Removal of a Director",subListTitlePay: "3305",pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Increase in Authorized Capital of your Company",subListTitlePay: "12899",pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Close your Private Limited Company",subListTitlePay: "21211",pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Change the Objectives of Your Company",subListTitlePay: "6304",pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Change the Official Address of Your Company(Within the City)",subListTitlePay: "4305",pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Change your Company Name",subListTitlePay: "8551",pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
];

List<BusinessSetupModel> gstModel = [
  BusinessSetupModel(listTitle: "Goods & Service Tax Registration",subListTitlePay: "399",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "GST Filings",subListTitlePay: "",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
];


List<BusinessSetupModel> accountingModel = [
  BusinessSetupModel(listTitle: "Accounting and Book Keeping",subListTitlePay: "17994",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Payroll Services",subListTitlePay: "20059",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "File your TDS Returns",subListTitlePay: "2949",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "File your Income Tax Returns",subListTitlePay: "1179",pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
];


List<BusinessSetupModel> labourModel = [
  BusinessSetupModel(listTitle: "PF Registration",subListTitlePay: "2998",pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "ESI Registration",subListTitlePay: "2998",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Apply for Professional Tax Registration",subListTitlePay: "6219",pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Apply for Shops and Establishment Act Registration",subListTitlePay: "5629",pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Employee Stock Option Plan (ESOP)",subListTitlePay: "49999",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
];


List<BusinessSetupModel> changesLLPModel = [
  BusinessSetupModel(listTitle: "Adding a Designated Partner",subListTitlePay: "3051",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Change LLP Agreement",subListTitlePay: "2961",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Close your Limited Liability Partnership",subListTitlePay: "6999",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
];

List<BusinessSetupModel> convertBusinessModel = [
  BusinessSetupModel(listTitle: "Convert your Sole Proprietorship into a Private Limited Company",subListTitlePay: "15559",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Due Diligence of Company",subListTitlePay: "17699",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Convert your Partnership into an LLP",subListTitlePay: "11800",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Convert your Private Limited Company into a Public Limited Company",subListTitlePay: "12072",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Convert your Private Limited Company into an One Person Company",subListTitlePay: "13841",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
];