import 'package:igli_financial/view/more/My_Services/All_Services/Model/All_Services_model.dart';

List<BusinessSetupModel> corporateModel = [
  BusinessSetupModel(
      listTitle:
          "Get help from a Company Secretary for your Private Limited Company",
      subListTitleEx: "26458",
      pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle:
          "Get help from a Company Secretary for your Limited Liability Partnership",
      subListTitleEx: "5150",
      pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
];

List<BusinessSetupModel> changesPvtModel = [
  BusinessSetupModel(
      listTitle: "Appointment of a Director",
      subListTitleEx: "4815",
      pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "Removal of a Director",
      subListTitleEx: "3305",
      pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "Increase in Authorized Capital of your Company",
      subListTitleEx: "12899",
      pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "Close your Private Limited Company",
      subListTitleEx: "21211",
      pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "Change the Objectives of Your Company",
      subListTitleEx: "6304",
      pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "Change the Official Address of Your Company(Within the City)",
      subListTitleEx: "4305",
      pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "Change your Company Name",
      subListTitleEx: "8551",
      pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
];

List<BusinessSetupModel> gstModel = [
  BusinessSetupModel(
      listTitle: "Goods & Service Tax Registration",
      subListTitleEx: "399",
      pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "GST Filings",
      subListTitleEx: "",
      pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
];

List<BusinessSetupModel> accountingModel = [
  BusinessSetupModel(
      listTitle: "Accounting and Book Keeping",
      subListTitleEx: "17994",
      pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "Payroll Services",
      subListTitleEx: "20059",
      pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "File your TDS Returns",
      subListTitleEx: "2949",
      pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "File your Income Tax Returns",
      subListTitleEx: "1179",
      pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
];

List<BusinessSetupModel> labourModel = [
  BusinessSetupModel(
      listTitle: "PF Registration",
      subListTitleEx: "2998",
      pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "ESI Registration",
      subListTitleEx: "2998",
      pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "Apply for Professional Tax Registration",
      subListTitleEx: "6219",
      pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "Apply for Shops and Establishment Act Registration",
      subListTitleEx: "5629",
      pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "Employee Stock Option Plan (ESOP)",
      subListTitleEx: "49999",
      pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
];

List<BusinessSetupModel> changesLLPModel = [
  BusinessSetupModel(
      listTitle: "Adding a Designated Partner",
      subListTitleEx: "3051",
      pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "Change LLP Agreement",
      subListTitleEx: "2961",
      pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "Close your Limited Liability Partnership",
      subListTitleEx: "6999",
      pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
];

List<BusinessSetupModel> convertBusinessModel = [
  BusinessSetupModel(
      listTitle:
          "Convert your Sole Proprietorship into a Private Limited Company",
      subListTitleEx: "15559",
      pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "Due Diligence of Company",
      subListTitleEx: "17699",
      pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "Convert your Partnership into an LLP",
      subListTitleEx: "11800",
      pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle:
          "Convert your Private Limited Company into a Public Limited Company",
      subListTitleEx: "12072",
      pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle:
          "Convert your Private Limited Company into an One Person Company",
      subListTitleEx: "13841",
      pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
];
