






import 'package:igli_financial/view/more/My_Services/All_Services/Model/All_Services_model.dart';

List<BusinessSetupModel> trademarkModel = [
  BusinessSetupModel(listTitle: "Trademark Registration",subListTitlePay: "6955",pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Respond to a Trademark Objection",subListTitlePay: "3539",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Apply for a Trademark in the U.S",subListTitlePay: "59129",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Logo design basic",subListTitlePay: "2950",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Trademark Watch",subListTitlePay: "1770",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Renew your Trademark",subListTitlePay: "8055",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Assign Your Trademark",subListTitlePay: "2869",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
];

List<BusinessSetupModel> patentModel = [
  BusinessSetupModel(listTitle: "Patent Search",subListTitlePay: "11899",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Apply for a Provisional Patent",subListTitlePay: "15957",pay: "",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(listTitle: "Apply for a Patent",subListTitlePay: "33657",pay: "Pay ₹499/-to get started",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),

];

