import 'package:igli_financial/view/more/My_Services/All_Services/Model/All_Services_model.dart';

List<BusinessSetupModel> trademarkModel = [
  BusinessSetupModel(
      listTitle: "Basic Trademark Registration",
      subListTitleEx: "5761",
      subListTitleIn: "5988",
      pay: "227",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "Premium Trademark Registration",
      subListTitleEx: "11532",
      subListTitleIn: "11988",
      pay: "456",
      description:
          "Trademark Filling Under One Class For Large Enterprises not Eligible of MSME Registration.",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "Design Registration",
      subListTitleEx: "6846",
      subListTitleIn: "7899",
      pay: "1053",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "Provisional Patent Registration",
      subListTitleEx: "59236",
      subListTitleIn: "69899",
      pay: "10663",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "Trademark Renewal",
      subListTitleEx: "12304",
      subListTitleIn: "12899",
      pay: "595",
      description:
          "Trademark Filling Under One Class For Proprietorship and Small Enterprises.",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "Patent Registration",
      subListTitleEx: "59236",
      subListTitleIn: "69899",
      pay: "10663",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
  BusinessSetupModel(
      listTitle: "Copyright Registration",
      subListTitleEx: "12304",
      subListTitleIn: "12899",
      pay: "595",
      description: "",
      duration: "",
      deliverables: "",
      penalty: "",
      benefits: "",
      documents: "",
      deliverablesTab: ""),
];
