// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkTbQ4lGOhYvJM8YV98G4tJd57EDsXhhQ',
    appId: '1:429122042514:web:052e8d47d2bdfef852444b',
    messagingSenderId: '429122042514',
    projectId: 'igli-financial-535e0',
    authDomain: 'igli-financial-535e0.firebaseapp.com',
    storageBucket: 'igli-financial-535e0.appspot.com',
    measurementId: 'G-SQN3MQLS4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcrWcy4-L7d7PEzDrobMEhdZaUrv9epns',
    appId: '1:429122042514:android:56c9a3ece3a4ea5752444b',
    messagingSenderId: '429122042514',
    projectId: 'igli-financial-535e0',
    storageBucket: 'igli-financial-535e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkV-6D6Uruga90EDHNH8OnA9pYUt7aNhc',
    appId: '1:429122042514:ios:826871ae136984db52444b',
    messagingSenderId: '429122042514',
    projectId: 'igli-financial-535e0',
    storageBucket: 'igli-financial-535e0.appspot.com',
    iosClientId: '429122042514-f6e65vjut6j1ml9isbut82c4rfjf2l4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.igliFinancial',
  );
}
